using System.Collections.Generic;
using System.Data;

namespace Dapper.Hat.SqlServer
{
    /// <summary>
    /// Interface for database command parameters.
    /// <see cref="IDatabaseConnectionFactory.CreateParameters()"/>
    /// </summary>
    public interface IDatabaseCommandParameters
    {
        /// <summary>
        /// Add scalar command parameter.
        /// </summary>
        void Add<T>(
            string name,
            T value,
            DbType? dbType = null,
            ParameterDirection direction = ParameterDirection.Input,
            int? size = null);

        /// <summary>
        /// Add scalar output parameter.
        /// </summary>
        void AddOutput(
            string name,
            DbType dbType,
            int? size = null);

        /// <summary>
        /// Add stored procedure return value parameter.
        /// </summary>
        /// <remarks>
        /// Parameter value is generated by stored procedure RETURN statement.
        /// <see href="https://msdn.microsoft.com/en-us/library/ms174998.aspx"/>
        /// </remarks>
        void AddReturnValue(string name = "@result");

        /// <summary>
        /// Add table-value parameter
        /// </summary>
        void AddTable<T>(string name, IEnumerable<T> tvp)
            where T : class;

        /// <summary>
        /// Get scalar parameter value
        /// </summary>
        T Get<T>(string name);
    }
}